### ISSUE TITLE
Avoid sliders to cross when multirange used

### ISSUE THREAD

**Issue by poco06** [seiyria/bootstrap-slider#730] opened 2017-03-19 15:27 UTC
Hello,

I'm using the multirange slider and would like to avoid the 2 sliders (left and right) crossed together. Normally, when you use this kind of slider range, the min value is on the left and should stay on the left and the same for the max value on the right.

Is there a way to avoid the 2 sliders crossed (ie meaning the right slider becomes the left slider and vice versa).

Regards
Pat

**Comment by seiyria** [comment] 2017-03-19 15:28
duplicate of #707

**Closed by seiyria** 2017-03-19 15:28 UTC
