### ISSUE TITLE
Slider doesn't work when container has position: relative?

### ISSUE THREAD

**Issue by xps** [seiyria/bootstrap-slider#355] opened 2015-04-07 22:18 UTC
Hi,

There seems to be an issue when the slider's container has `position: relative`:
http://codepen.io/anon/pen/JoqmPZ

Or am I missing something?

As far as I can tell, the problem lies in the `_getPercentage` function, specifically [this line][1], as the offset is returned relative to the closed positioned parent, but the event mouse coordinates are relative to the page.

For what I do, I did a dirty patch using JQuery's offset() function instead but clearly the original method dealt with more use cases:

    var sliderOffset = $(this.sliderElem).offset()[this.stylePos];

  [1]: https://github.com/seiyria/bootstrap-slider/blob/master/js/bootstrap-slider.js#L1247

**Comment by seiyria** [comment] 2015-04-07 22:30
I believe this is a duplicate of #340.

**Closed by seiyria** 2015-04-07 22:30 UTC
