### ISSUE TITLE
RANGE SLIDER: Add option for snaps array; different snaps for each handler 

### ISSUE THREAD

**Issue by klihelp** [seiyria/bootstrap-slider#930] opened 2019-07-26 05:47 UTC
Add support to snaps array.

Currently there is only one snap setting for every handle, really low or really high value would need to accmodate click/drag/touch around the handler more realistically.

**Comment by seiyria** [comment] 2019-07-26 13:11
duplicate of #750

**Closed by seiyria** 2019-07-26 13:11 UTC

**Comment by klihelp** [comment] 2019-07-29 09:24
Steps between the ranges are slightly related to the snap close to the range edge true.
