### ISSUE TITLE
Ticks and bottom margin are not set properly when slider is initialized under a container whose display is none

### ISSUE THREAD

**Issue by rayHInstart** [seiyria/bootstrap-slider#450] opened 2015-09-23 01:57 UTC
It looks like the slider is looking for its size in _layout, but this._state.size is 0 because it is hidden and thus takes up no size. When the slider's container is displayed, the slider doesn't call _layout, and so the ticks aren't given the proper width and the bottom margin is messed up.
Ran across this problem on a project I'm working on and it took half a day to figure it out. I'm slow and was looking for an error somewhere in my own code.

**Comment by seiyria** [comment] 2015-09-23 12:30
duplicate of #162

**Closed by seiyria** 2015-09-23 12:30 UTC
