### ISSUE TITLE
How to limit handle range min max ??

### ISSUE THREAD

**Issue by wokung** [seiyria/bootstrap-slider#372] opened 2015-05-13 12:41 UTC
Hi,

I replaced the handle of bootstrap slider with a background image of size 39px x 39px.

Now I want to limit the range of my bootstrap slider handle as seen on the second example. 

http://jsfiddle.net/jtjrxu3m/1/

However, how do I fix it in a way that the handle does not get out of range of the track?

thanks!!

**Comment by seiyria** [comment] 2015-05-13 13:00
I'm quite confused. What is your limit condition exactly? One slider being limited by another slider? Or one slider is just limited by itself somehow?

**Comment by wokung** [comment] 2015-05-13 13:14
hey,

thanks for your answer.

My limit is, that I can't style the Lower and Upper Track of the Slider in webkit and mozilla browser with input type = range.

Thats why I used the bootstrap slider, in order to style the lower track.

But somehow, the Slider Handle overlaps the Slider Track, what does not suite my design.

The second slider with input type range is styled correctly, but has no lower track color, what makes it unuseable for my problem.

**Comment by seiyria** [comment] 2015-05-13 14:10
Honestly, even with this jsfiddle, I'm struggling to understand what you're getting at. I'm seeing this:

![](http://i.imgur.com/LhdIwe0.png)

and that appears to be the correct behavior for styling the lower track.

**Comment by wokung** [comment] 2015-05-13 14:34
Yes. But the Problem is that the handle of the first slider overlaps the end of the track. I need it to be inside the track. Like the second slider.

**Comment by seiyria** [comment] 2015-05-13 14:43
I think that's a byproduct of the size of your handle, and I don't think there's anything we can do about that.

**Comment by wokung** [comment] 2015-05-13 14:59
Hey,
thanks, I already assumed that this is the case.

However, I thought about adding another option to cover this use case.

It should be possible if the slider also includes the width of the handle in his calculations, since I suppose at the moment it is calculated with width/2 for placing the handle.

Thanks anyways !!!

**Comment by seiyria** [comment] 2015-05-13 15:13
Possible, but I don't think we actively support that. We'd probably be willing to take it in a PR, but for now, I'm going to close this as it's not intended behavior. Feel free to submit a PR if you get your use case working!

**Closed by seiyria** 2015-05-13 15:13 UTC
