### ISSUE TITLE
Value[0] can be greater than value[1] in range slider

### ISSUE THREAD

**Issue by pbowman-rmn** [seiyria/bootstrap-slider#547] opened 2016-03-17 01:54 UTC
If you set both values equal in a range slider then click left of the value, value[1] will be set to the low value while value[0] is set to the high value. This shouldn't happen as value[0] should always be <= value[1]. This is easily reproducible in examples 2 or 16 on http://seiyria.com/bootstrap-slider/. As you click around it keeps this inverted order but the tiniest drag will snap back to the correct order.

![value0 greater than value1](https://cloud.githubusercontent.com/assets/4722221/13833837/8d6a6216-ebb7-11e5-80a6-619141c9f29c.png)

**Comment by seiyria** [comment] 2016-03-17 01:59
Likely a duplicate of #283. I'll close that one in favor of this one as this has more information.

**Comment by henriklundahl** [comment] 2016-04-03 19:22
Perhaps that's a different error, but it's also possible to get this behavior when using the keyboard to move the handles.

**Comment by ziofat** [comment] 2016-04-26 01:13
This is also a duplicate of #435 which has a gif for this issue.

**Closed** 2016-04-26 01:20 UTC
