### ISSUE TITLE
Init multiple sliders at once (without jQuery)

### ISSUE THREAD

**Issue by SiamKreative** [seiyria/bootstrap-slider#349] opened 2015-03-31 10:21 UTC
Hi there,

I have not been able to get this working: `new Slider('.slider');`. Please see this jsfiddle I created: http://jsfiddle.net/SiamKreative/hu35eh2o/

I want to initialize multiple sliders at once, with a class. What am I doing wrong?

Thanks

**Comment by seiyria** [comment] 2015-03-31 12:55
I'm pretty sure this will only work with jquery using the workaround in #247. This is essentially a duplicate of that as far as I can tell (regardless of the jquery difference).

**Closed by seiyria** 2015-03-31 12:55 UTC

**Comment by SiamKreative** [comment] 2015-03-31 13:14
I saw that topic and I'm struggling to replicate this in vanilla JS. I tried the following:
```javascript
var slider = document.getElementsByClassName('slider');
for (i = 0; i < slider.length; ++i) {
	item = '#' + slider[i].getAttribute('id');
	new Slider(item);
}
```

But it doesn't work. Any help would be greatly appreciated :)

**Comment by seiyria** [comment] 2015-03-31 13:19
Just do something like:

```js
var sliders = document.getElementsByClassName('slider');
sliders.forEach(function(slider) { new Slider(slider); } );
```

As you can see [here](https://github.com/seiyria/bootstrap-slider/blob/master/js/bootstrap-slider.js#L264) the slider constructor can take an HTMLElement too.

**Comment by SiamKreative** [comment] 2015-03-31 13:28
Thanks @seiyria ! Unfortunately, this gives me the following:

![image](https://cloud.githubusercontent.com/assets/1778633/6919829/7005e4c6-d7e4-11e4-9875-98f3db79c0e9.png)

**Comment by SiamKreative** [comment] 2015-03-31 13:43
Looks like I was able to figure out why: http://stackoverflow.com/a/24266344/1414881

So my code is the following:
```javascript
[].forEach.call(document.getElementsByClassName('slider'), function (v, i, a) {
	console.log(a[i]);
	// new Slider(a[i]);
});
```

This works as I see the objects:
![image](https://cloud.githubusercontent.com/assets/1778633/6920050/49d04182-d7e6-11e4-894a-d01d1938bf58.png)

But if I un-comment `new Slider(a[i]);`, then here is what I see:
![image](https://cloud.githubusercontent.com/assets/1778633/6920093/83246b34-d7e6-11e4-9f71-6f3d2d74a352.png)
![image](https://cloud.githubusercontent.com/assets/1778633/6920077/65790dba-d7e6-11e4-9a35-757eab7f47ca.png)

I struggle to understand what's happening...

**Comment by SiamKreative** [comment] 2015-03-31 13:52
Oh god. I finally got it right. The class "slider" was being using by the plugin. I simply renamed it to "whatever" and it worked perfectly. Thanks for your help.

**Comment by seiyria** [comment] 2015-03-31 13:53
No problem.
