### ISSUE TITLE
Tooltip on slide not shown on iPhone

### ISSUE THREAD

**Issue by kikrahau** [seiyria/bootstrap-slider#520] opened 2016-02-04 12:34 UTC
Hi,

the tooltips are not shown on my iPhone when use the Slider. Is this a common issue and does anyone know an easy fix?

Thanks!

Tried on iPhone 6, 9.2

**Comment by seiyria** [comment] 2016-02-04 12:44
This is a duplicate of #513.

**Closed by seiyria** 2016-02-04 12:44 UTC
