### ISSUE TITLE
Prevent selectors from being dragged over each other ??

### ISSUE THREAD

**Issue by patrioticcow** [seiyria/bootstrap-slider#733] opened 2017-03-23 21:00 UTC
I would like to disable dragging one selector over the second one.
Here is some code that does that, but  something out of the box would be more elegant.

[http://jsbin.com/kopakiciti/1/edit?html,js,output](http://jsbin.com/kopakiciti/1/edit?html,js,output)

**Comment by seiyria** [comment] 2017-03-23 21:01
duplicate of #707

**Closed by seiyria** 2017-03-23 21:01 UTC
