### ISSUE TITLE
Slider tooltip-main doesn't show under bootstrap 4.0.0

### ISSUE THREAD

**Issue by tianfudhe** [seiyria/bootstrap-slider#817] opened 2018-02-07 01:53 UTC
hello, Seiyria.
I notice that your slider plugin does not show tooltip under bootstrap-4.0.0.

**Analysis and suggestion:**
And I find that in your code, tooltip opacity is controlled by class `.tooltip.in` , however in bootstrap 4, it is
```
.tooltip.show {
  opacity: 0.9;
}
```

And this is the reason why this issue happens. it would be great if you adress it.

**Comment by seiyria** [comment] 2018-02-07 01:56
Duplicate of #689

You're welcome to submit a PR for this.

**Closed by seiyria** 2018-02-07 01:56 UTC
