### ISSUE TITLE
Example 6 - if clicked to select position

### ISSUE THREAD

**Issue by RobEDarling** [seiyria/bootstrap-slider#552] opened 2016-04-03 18:18 UTC
Awesome plugin... Something I noticed when reviewing your examples.  
If you look at example 6 on your examples page - if the user does not use the slider but instead clicks on a location in the slider - the value you display in #ex6SliderVal will not update because it is using the slide event to get its value.  Is there another event  way to capture the event for this and update the label?

**Comment by seiyria** [comment] 2016-04-03 18:19
Duplicate of https://github.com/seiyria/bootstrap-slider/issues/550

Use the change event.

**Closed by seiyria** 2016-04-03 18:19 UTC

**Comment by RobEDarling** [comment] 2016-04-03 19:01
Sorry for the duplicate - I did search but it seems like #550 and #491 both used very different ways to explain this.  
Maybe this post will help reduce duplicates or at least help others with an answer:
            $("#ex6").on("change", function() {
                $("#ex6SliderVal").text($("#ex6").val());
            });
This works for both sliding or clicking a point on the slider.

Cheers!
