### ISSUE TITLE
Prevent lower range handle from going above upper handle?

### ISSUE THREAD

**Issue by euwyn** [seiyria/bootstrap-slider#471] opened 2015-11-02 23:07 UTC
It seems odd that a user can drag the lower bound of the range handle to move "above" the upper bound range handler. Should this be preventable?

**Comment by seiyria** [comment] 2015-11-02 23:11
The lower bound simply becomes the higher bound in this case. Whether or not it's advisable, I'm not sure. I can see it being both a good and bad feature.

**Comment by seiyria** [comment] 2016-01-08 23:58
duplicate of #283

**Closed by seiyria** 2016-01-08 23:58 UTC
