### ISSUE TITLE
Tooltip stopped working with bootstrap 4

### ISSUE THREAD

**Issue by mooodin** [seiyria/bootstrap-slider#767] opened 2017-07-24 18:07 UTC
To reproduce the issue simply change the bootstrap file in the dependencies Folder.
Hi Kyle, Hi Rohit,
Do you have plans to update this fine Slider to the current Bootstrap 4 Version?
Thanks & Cheers
Martin

**Comment by seiyria** [comment] 2017-07-24 18:08
Duplicate of #689

**Closed by seiyria** 2017-07-24 18:08 UTC
