### ISSUE TITLE
[Feature Request] Range Sliders- Minimum distance

### ISSUE THREAD

**Issue by Fieora** [seiyria/bootstrap-slider#743] opened 2017-04-28 17:30 UTC
I have been working to find a solution, but having no luck, creating a range slider where the two ranges can't be within a certain distance of each other. If anyone has any ideas that work within the current system please let me know! 

--thanks

**Comment by seiyria** [comment] 2017-04-28 17:38
duplicate of #32.

**Closed by seiyria** 2017-04-28 17:38 UTC
