### ISSUE TITLE
Event-Callbacks given through Constructor do not work

### ISSUE THREAD

**Issue by henlen** [seiyria/bootstrap-slider#602] opened 2016-07-20 06:11 UTC
Heyho!

This is maybe not a bug, but you can't put callbacks in the slider-options.
See: https://jsfiddle.net/x36kwg3f/

Maybe you have a little time for a nice fix. Would be cool. :-)
It's just I like it compact.

HenLen

**Comment by seiyria** [comment] 2016-07-20 13:24
duplicate of #486. long and short of it is we'll accept a PR, but it's not anything we are interested in adding.

**Closed** 2016-08-06 03:10 UTC
