### ISSUE TITLE
Can't set range sliders values via JQuery

### ISSUE THREAD

**Issue by mfaorlkzus** [seiyria/bootstrap-slider#769] opened 2017-08-03 12:32 UTC
Hello, I use the range slider to display time ranges. When the user changes a day, the range slider handles should be places where the selected days values are. So I have to change the position of the min-slider and the max-slider everytime when the user changes a day. Here is my code:

HTML
```
<p id="start-time-label"></p>
<input type="text" name="slider" id="time-slider">
<p id="stop-time-label"></p>
```

JQuery
$(document).ready(function(){
	// show Slider

	$("#time-slider").slider({
          range: true,
          min: 0,
          max: 1439,
          step: 15,
          value: [0, 1439],
          slide: slideTime
	});

	// change day btn
	$('.day-btn').click(function(){
          var start = // get start time;
          var end = // get stop time;
          $("#time-slider").setAttribute('values', [start, end]);
	});

**Comment by seiyria** [comment] 2017-08-03 13:18
Duplicate of #711

**Closed by seiyria** 2017-08-03 13:18 UTC
