### ISSUE TITLE
How to disallow values that are not in ticks array

### ISSUE THREAD

**Issue by john-clarke** [seiyria/bootstrap-slider#535] opened 2016-03-03 17:06 UTC
I want to disallow values that are not tick values for a series of numbers that does not follow a single step value.

```
$("input").slider({ 
  ticks: [2015, 2016, 2018, 2020],
  ticks_labels: ["2015", "2016", "2018", "2020"],
  ticks_positions: [0, 33, 66, 100],
});
```
Currently allows the user to select 2017 and 2019 (mouse and/or keyboard). I don't want the user to be able to select these values.

https://jsfiddle.net/7ej9mmwx/2/

Is this possible?

**Comment by seiyria** [comment] 2016-03-03 17:07
duplicate of #534.

Just use ticks 1-4 and use the formatter/etc as you are, then change the value when you slide it.

**Comment by john-clarke** [comment] 2016-03-03 17:47
Thank you. This is a good workaround. I'd prefer getting the actual value (not 1,2,3,4) back on change events etc.

**Comment by seiyria** [comment] 2016-03-03 17:47
Your best bet then is to format the output in the same fashion that you format the display of it (ie, the formatter function).

**Comment by mediaformat** [comment] 2016-10-25 19:39
Following up with this issue (though not sure if I should open a new one), I have managed to display the _actual_ value using formatter, however the _aria-valuenow_ does not reflect the actual value. Additionally the _aria-valuemin_ and _aria-valuemax_ should reflect the _actual_ values.

See : https://jsfiddle.net/bbw6z63n/

**Comment by mediaformat** [comment] 2016-10-26 14:21
It seems that  _aria-valuenow_ is correct and that the _aria-valuetext_ would be suited for precisely this use case.

> Authors SHOULD only set the aria-valuetext attribute when the rendered value cannot be accurately represented as a number. *

`<div role="slider" aria-valuenow="1" 
	aria-valuemin="1" aria-valuemax="7"
	aria-valuetext="Sunday">`

*Albeit, still a number, in my [case](https://jsfiddle.net/bbw6z63n/1/) the number is not the _proper_ one, a small and acceptable exception IMO.

Perhaps, whenever the formatter is used, the aria-valuetext should reflect the formatter value. (Feature request)

aria-valuetext : https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-valuetext_attribute

**Comment by seiyria** [comment] 2016-10-26 14:23
If you'd like to make this into a feature request, I'd recommend opening a new issue as this thread has diverged from the original issue.

**Closed** 2016-10-26 15:25 UTC
