### ISSUE TITLE
Problem with multiple libraries

### ISSUE THREAD

**Issue by ffcc** [seiyria/bootstrap-slider#530] opened 2016-02-23 00:06 UTC
I have multiple libraries (jQuery including) that overrides the window.define function and I need the Slider added to the window object (window.Slider = factory(jQuery)). How can I force this to fix the problem with other libraries?

**Comment by seiyria** [comment] 2016-02-23 00:12
It sounds like you need to fix your environment, use bridget, or something else. AFAIK, we follow AMD so if something breaks that, there's not much we can do.

**Comment by ffcc** [comment] 2016-02-23 01:42
I work with bower and have a lot of dependencies on my project. When I add bootstrap-slider as a dependency and follow the simple example with and without jQuery it seems the window.Slider is not register in both the window and the jQuery object. In case of AMD I'm not explicit use require or something like that.

**Comment by rovolution** [comment] 2016-02-23 01:48
could you provide a Fiddle with an example? Thanks!

**Comment by ffcc** [comment] 2016-02-23 02:06
In case I can't fix my environment I will provide an example with Fiddle. Thanks!

**Comment by seiyria** [comment] 2016-06-01 13:40
duplicate of #575 and others. Closing this one.

**Closed by seiyria** 2016-06-01 13:40 UTC
