### ISSUE TITLE
Bug in Bootstra 3 modal

### ISSUE THREAD

**Issue by EkaCreativeSolutions** [seiyria/bootstrap-slider#358] opened 2015-04-09 21:02 UTC
Hi,
I have a bug, when i use slider in a bootstrap modal.
When i click on slider, the handle go to max valua with relative tooltip and block in that position.
Bootstrap modal, open with classic button with href="#modal".

Out of modal, slider work correctly.
Sorry for my english.

**Comment by seiyria** [comment] 2015-04-09 21:07
Probably a duplicate of #340, but we'd need an actual example here.

**Closed by seiyria** 2015-04-09 21:07 UTC

**Comment by jonathan-opinurate** [comment] 2015-11-24 11:06
I have an issue with the modal slider too.

Whenever I click the next button, the slides come in from the right, but the issue isn't that they come in from the right, that's fine, the problem is the content is showing before it fits in the modal space. however when I use the previous button, the slide comes from the left to the previous slide normally.

**Comment by jonathan-opinurate** [comment] 2015-11-24 11:14
http://webm.host/344c5/vid.webm

see my issue here.

**Comment by seiyria** [comment] 2015-11-24 13:42
For that, I would expect that you should just set the modal to a static height while transitioning in content.

However, a webm is not a valid example. We ask for fiddles for repros because we can actually try them - we can't try a video.

**Comment by jonathan-opinurate** [comment] 2015-11-24 14:50
fair enough, I managed to sort it out anyways, I removed the slide class from the console, so that it didn't slide in and fits better to my modal's needs anyways.

I will keep that in mind for future (using JsFiddle etc...)

Thanks,
Jonathan
