### ISSUE TITLE
Slider not working inside bootstrap comun grid columns

### ISSUE THREAD

**Issue by sades** [seiyria/bootstrap-slider#327] opened 2015-03-07 02:35 UTC
Hi, I am trying to use this slider but when its placed inside any div that has a class="col-md-6 for example it does not work correctly none of the col-*-* are working when placed inside those divs and you try to slide it just goes to the end of the slide.

**Comment by seiyria** [comment] 2015-03-07 02:36
Did you add the col-md-12 class to the slider itself?

**Comment by sades** [comment] 2015-03-07 02:38
no i even try reproducing this http://jsfiddle.net/2DygG/7/ it seems to work fine in the fiddle because the limits of the iframe are small but out of it it wont work

**Comment by seiyria** [comment] 2015-03-07 02:39
It's not because of the iframe, it's because of this:

```
<input style="width: 100%;" />
```

Did you try this?

**Comment by sades** [comment] 2015-03-07 02:45
yes i did if you open that fiddle http://jsfiddle.net/2DygG/7/  and do this 
![01](https://cloud.githubusercontent.com/assets/271004/6539721/f2736324-c449-11e4-9233-aae9652dcc3e.jpg)
Just click on it and it will go directly to the end to move it you basically have to click over it and hold the mouse and move it to the end of the screen

**Comment by seiyria** [comment] 2015-03-07 02:46
Strange, but I can repro this now at least.

**Comment by sades** [comment] 2015-03-07 02:49
Im on a resolution of 1920x1080 i changed to 1024x762 and it worked almost perfectly seems it doesn't like big screens or resolutions, tested on my 15 inch labtop also and works better than on the 22 inch screen but still you have to move way more to the borders of the screen

**Comment by sades** [comment] 2015-03-07 03:05
Ok doing some more test I decided to place direct styles to the div that contains the slider but simulating bootstrap styles, what I encounter is that the position relative that have bootstrap divs cause the marker to function incorrectly

Example
<div style="width:90%; float:left; min-height: 1px;  padding-left: 15px; padding-right: 15px; position: relative;">

When i test the same div but without the position relative like this:

<div style="width:90%; float:left; min-height: 1px;  padding-left: 15px; padding-right: 15px;">

It works like a charm, hope this helps to get a fix around

**Comment by shammar13** [comment] 2015-03-08 08:21
@sades, I've got the same issue. I have also found that setting the position of the divs that contain the slider to be static fixes the issue.

Maybe there is an error in how the position of the mouse/click is calculated when the slider is in a relative div?

@seiyria, I found another way for you to reproduce the issue. Go to your examples page (http://seiyria.github.io/bootstrap-slider/) and then inspect element on one of the `.well` elements and then just add the style `position: relative;` and then try dragging the slider around.

**Comment by crevete** [comment] 2015-03-09 11:52
@seiyria I've got this issue too... Please not that this was introduced this weekend. I mean, in the version 4.5.1, this does not exist. Please review what you have changed between 4.5.1 and 4.5.4 and get it fixed ASAP. Actually the slider is "NOT" usable...

**Comment by seiyria** [comment] 2015-03-09 12:27
Just use 4.5.1 then if it's urgent.

**Comment by threeaims** [comment] 2015-03-12 15:42
Hi seiyria, 

Thanks for the open source work. Much appreciated.

I've found a similar issue to this and I too need a slider to work inside a bootstrap grid. Luckily the workaround isn't too hard - since 4.5.1 isn't on npm, I've tested both 4.5.0 and 4.5.2 via npm. Both work fine, and don't have this bug on Chrome or Safari at least.

For others following I suggest just using 4.5.2 until this critical issue can be prioritised.

Thanks again.

**Comment by raefa** [comment] 2015-03-12 19:58
If you have multiple levels of columns (i.e. you set the layout with a grid and then you position the slider in another grid) the issue still remains. A quick workaround is setting "position: initial" on the parent column.
`<div class="col-sm-7" style="position: initial">`

**Comment by crevete** [comment] 2015-03-12 22:27
@raefa your workaround does not work inside a modal... the bug is clearly on the "position" attribute. Since the slider does not work, but you can still drag it to left side to get the value you want (if you just clic on the slider to get the wanted value, it's just impossible...)

**Comment by raefa** [comment] 2015-03-12 23:41
@crevete You are right. I have also found it does not work in IE11! Will post a solution if I find it.

**Comment by raefa** [comment] 2015-03-13 00:19
@crevete Next ugly hack! 
`<div class="col-sm-7" style="position: static">`
Fixed the issue for me in IE11 and still works elsewhere. I can't work out why this works or what the cause is but it seems to work.

**Comment by crevete** [comment] 2015-03-13 00:44
@raefa LOL I've tried ```position:static;``` too, but inside a modal, it still does not work...

**Comment by mark47** [comment] 2015-03-14 00:32
I just submitted a pull request that seems to resolve this issue. Needed to revert the change made to `_offset` in [this commit](https://github.com/seiyria/bootstrap-slider/commit/e494bc35c1f0462200ab9218085aba6826047eb2).

Replaced with this older version of the offset code:

		    _offset: function (obj) {
				var rect = obj.getBoundingClientRect(),
					ol = rect.left,
					ot = rect.top;

				return {
					left: ol,
					top: ot
				};
			},

**Comment by crevete** [comment] 2015-03-14 09:02
@mark47 You are right :+1: But why you closes your PR ???

@rovolution @seiyria Here is the fix : http://jsfiddle.net/2DygG/11/ and please make a new tag 4.5.5 for this immediately...

**Comment by mark47** [comment] 2015-03-14 15:35
I was having some problems with my Git client yesterday which caused some unnecessary commits. Thanks for your pull request, @crevete

**Comment by rovolution** [comment] 2015-03-14 17:36
hi everyone

we made a fix for this and tagged at 4.5.6

**Comment by mark47** [comment] 2015-03-14 19:59
Thanks @rovolution -- I appreciate all the work you and @seiyria have put into this project! Cheers.

**Closed** 2015-03-14 22:32 UTC
