### ISSUE TITLE
Tooltips do not hide on Firefox

### ISSUE THREAD

**Issue by lukaszgrolik** [seiyria/bootstrap-slider#232] opened 2014-10-12 08:46 UTC
I'm using Firefox 32.0.3 on Mint 17, but this issue probably affects Ubuntu as well. I don't know about Windows.

![seiyria-bootstrap-slider-firefox-issue](https://cloud.githubusercontent.com/assets/3110622/4605542/d3a8685a-51e8-11e4-8610-151eb4a1e38c.gif)

Tooltips disappear only when scrolling the page. 

[JSFiddle](http://jsfiddle.net/as502ak6/1/)

**Comment by pelegm** [comment] 2015-04-16 15:10
I confirm this bug on Ubuntu 14.04, firefox 37.0.1.

**Comment by kmkroski** [comment] 2015-08-03 05:26
I'm seeing the same issue on Chrome 44 on OSX 10.10.4.

**Comment by kmkroski** [comment] 2015-08-03 05:39
I've found a fix: on line 318, set inDrag to false. 
`inDrag: false,`

**Comment by seiyria** [comment] 2015-08-03 12:13
Want to submit a PR @kmkroski?

**Comment by AidasK** [comment] 2015-09-02 10:46
Fix is working, merge please :+1:

**Comment by seiyria** [comment] 2015-09-02 12:39
If we don't have a suitable test to back it up, a fix doesn't really mean
much.

**Comment by AidasK** [comment] 2015-09-02 12:59
But it is a must, I cant use this library without it. And maybe this fix won't break any of existing tests.

**Comment by seiyria** [comment] 2015-09-02 13:31
It's not that this fix will break any existing tests, it's that this fix, without a test, can be broken later.

**Comment by AidasK** [comment] 2015-09-02 13:35
But it could work now and it is broken in current version anyway.

**Comment by seiyria** [comment] 2015-09-02 13:49
Then please feel free to submit a PR with an accompanying unit test so, going forward, this doesn't happen again.

**Comment by Bhoft** [comment] 2015-09-03 13:07
He should write a test for some bug which was introduced by @rovolution by this commit https://github.com/seiyria/bootstrap-slider/commit/4942c1bc393d7051d82f482e318fc669e4953536 and wasn't captured by a unit test because he wanted to have one parameter set to false instead of null.
This is strange.... btw please also then fix the _state.over which is also set to null by default. Both parameters had default values of false in the older versions btw.

**Comment by rovolution** [comment] 2015-09-03 14:24
@Bhoft can you not just create your own fork, make the fix, and then use your fork for the time being? That is the whole point of open source.

**Comment by Bhoft** [comment] 2015-09-03 14:35
@rovolution of course ;) i never wanted to sound unthankful for your work.
I also already fixed it in my fork ;)

**Comment by seiyria** [comment] 2015-09-03 14:39
@Bhoft Bugs are unknowingly introduced at times, that's unpreventable. What we can prevent is having those same bugs going forward.

You are right, we don't have time to maintain this project but we both make every effort we can to ensure incoming issues, PRs, etc are good before they get merged or taken on. This is part of the reason we have such a strict CONTRIBUTING.md. That said, this is neither of our primary projects. I no longer use it in production anywhere (this was my primary motivation for picking it up in the first place) so I just try to filter the incoming issues/PRs. I am not sure if @rovolution uses it in production but I know he's very busy as well.

This goes back to his point of technical debt. We don't have time to fix everything, and this is very much a community-driven project. That said, we don't want the community _as a whole_ to suffer from large amounts of technical debt because a few PRs got through without adequate testing, which might cause further regressions and problems. Yes, it moves slow, and yes, there will be bugs, and _yes_ - this will be broken. You are free and welcome to:

* revert to a previous version
* send us a _well-formed_ PR
* use your own fork

But we don't want to subscribe to the "do it later" philosophy - we're busy, so we can't expect that we'll come back and write tests at any point. That's why they're required before anything gets merged. You'd be surprised what's actually testable and what's not - it's all up to how persistent the developer writing the tests is.

Lastly, if there are other problems unrelated to those in this issue, please open a new issue. I know it may seem similar to this one but it's very easy to lose issues that are mentioned in the thread of another.

**Comment by seiyria** [comment] 2016-01-27 19:42
The fix got merged quite some time ago, I'll close this now.

**Closed by seiyria** 2016-01-27 19:42 UTC
